"""
I/O functions: parsers for K_POINTS, band files, and fatband/projwfc files.
Extracted verbatim from qep.py.
"""
import os
import glob
import re
import numpy as np


def parse_kpath_file(kpath_file):
    """
    Parses a Quantum ESPRESSO K_POINTS (crystal_b) file to extract the number of k-points
    for each path segment and the corresponding high-symmetry point labels.

    Parameters
    ----------
    kpath_file : str
        Path to the QE K_POINTS file (crystal_b format).

    Returns
    -------
    counts : list of int
        Number of k-points for each segment (i.e., between high-symmetry points).
    labels : list of str
        List of high-symmetry point labels in the path (e.g., 'G', 'K', 'M').

    Notes
    -----
    The function skips the last row of the K_POINTS file. This is intentional:
      - The last row typically only repeats the initial high-symmetry point to close the band path.
      - If you do NOT skip the last row, the code would count one more segment than actually exists,
        which leads to tick and segment misalignment in plotting.

    Example
    -------
    Given a file like:
        K_POINTS crystal_b
        4
          0.0000  0.0000  0.0  20  ! G
          0.5000  0.0000  0.0  30  ! M
          0.3333  0.3333  0.0  40  ! K
          0.0000  0.0000  0.0  20  ! G
    Output will be:
        counts = [20, 30, 40]
        labels = ['G', 'M', 'K', 'G']
    """
    entries = []
    with open(kpath_file, 'r') as f:
        lines = f.readlines()
    start = None
    for i, line in enumerate(lines):
        if line.strip().upper().startswith('K_POINTS'):
            start = i + 2
            break
    if start is None or start >= len(lines):
        raise ValueError(f"K_POINTS header not found or invalid in {kpath_file}")
    try:
        declared = int(lines[start - 1].split()[0])
    except (ValueError, IndexError):
        declared = None
    for line in lines[start:]:
        txt = line.strip()
        if not txt or txt.startswith('#'):
            continue
        parts = txt.split('!')
        vals = parts[0].split()
        try:
            cnt = int(vals[3])
        except Exception:
            cnt = 1
        lbl = parts[1].strip() if len(parts) > 1 else ''
        entries.append((cnt, lbl))
        if declared is not None and len(entries) >= declared:
            break
    if len(entries) < 2:
        raise ValueError(f"crystal_b path needs at least two vertices in {kpath_file}")
    # In QE crystal_b the last vertex has no outgoing segment. Preserve its
    # label for the final plot tick, but ignore its interpolation count.
    counts = [count for count, _label in entries[:-1]]
    labels = [label for _count, label in entries]
    return counts, labels


def read_band_xdistances(band_file, kpath_file):
    """
    Reads a Quantum ESPRESSO .bands.dat.gnu band file and a K_POINTS path file,
    and extracts all x-axis distances, band energies, tick locations, and segment ranges for plotting.

    Parameters
    ----------
    band_file : str
        Path to the QE .bands.dat.gnu file (typically generated by bands.x).
    kpath_file : str
        Path to the QE K_POINTS file in crystal_b format (see parse_kpath_file).

    Returns
    -------
    x_dist : np.ndarray, shape (N_k,)
        Distance along the k-path for each k-point (for x-axis).
    band_energies : np.ndarray, shape (N_bands, N_k)
        Energies for all bands at each k-point.
    tick_positions : list of float
        x-coordinates of high-symmetry points (used for vertical tick lines).
    tick_labels : list of str
        Corresponding labels for each tick (e.g., 'G', 'K', 'M', ...).
    seg_ranges : list of (int, int)
        Index ranges (start, end) for each band path segment.
    """
    # 1) read all lines and group into blocks
    with open(band_file, 'r') as f:
        raw = f.read().splitlines()
    blocks = []
    block = []
    for line in raw:
        if line.strip() == "":
            if block:
                blocks.append(block)
                block = []
        else:
            block.append(line)
    if block:
        blocks.append(block)

    # 2) parse each block
    band_arrays = []
    for blk in blocks:
        try:
            arr = np.loadtxt(blk)
        except Exception as e:
            raise ValueError(f"Failed to parse band block: {e}")
        if arr.ndim != 2 or arr.shape[1] < 2:
            raise ValueError(f"Unexpected block shape {arr.shape}")
        band_arrays.append(arr)

    if not band_arrays:
        raise ValueError(f"No bands found in {band_file}")

    # 3) ensure all blocks have same length
    lengths = [b.shape[0] for b in band_arrays]
    if len(set(lengths)) != 1:
        raise ValueError(f"Inconsistent k-points per band: {lengths}")
    N_k = lengths[0]

    # 4) extract x_dist and energies
    x_dist = band_arrays[0][:, 0].copy()
    band_energies = np.vstack([b[:, 1] for b in band_arrays])


    # 5) parse kpath
    counts, labels = parse_kpath_file(kpath_file)
    cum = np.cumsum([0] + counts)
    if cum[-1] != N_k:
        # adjust only by ±1, else warn
        if cum[-1] == N_k + 1:
            cum[-1] = N_k
        elif cum[-1] == N_k - 1:
            cum = np.append(cum, N_k)
            labels = labels + [labels[0] if labels else ""]
        else:
            print(f"Warning: sum(counts)={cum[-1]} != N_k={N_k}. Tick positions may be misaligned.")

    tick_positions, tick_labels = [], []
    for idx, lbl in zip(cum, labels):
        if idx > N_k:
            break
        point_index = N_k - 1 if idx == N_k else idx
        tick_positions.append(x_dist[point_index])
        tick_labels.append(lbl)

    # segment boundaries
    dx = np.diff(x_dist)
    breaks = np.where(dx < -1e-6)[0]
    seg_ranges = []
    start = 0
    for br in breaks:
        seg_ranges.append((start, br))
        start = br + 1
    seg_ranges.append((start, N_k - 1))

    return x_dist, band_energies, tick_positions, tick_labels, seg_ranges


def read_fatband_files(fatband_dir, spin=False, sub_orb=False):
    """
    Reads fatband/PDOS files from a directory and extracts labels and weights.

    Parameters
    ----------
    fatband_dir : str
        Directory containing PDOS/fatband files.
    spin : bool
        If True, looks for SOC filenames with j/mj info.
    sub_orb : bool
        If True, splits into sub-orbitals (m-resolved).
    """

    if spin:
        pattern = re.compile(r'atm#(\d+)\(([A-Za-z]+)\)_wfc#\d+\(([spdfgpxyz]+)(?:_j[0-9.]+)?\)')
        fallback = re.compile(r'atm#\d+\(([A-Za-z]+)\)_wfc#\d+\(([spdfgpxyz]+)(?:_j[0-9.]+)?\)')
    else:
        pattern = re.compile(r'atm#(\d+)\(([A-Za-z]+)\)_wfc#\d+\(([spdfgpxyz]+)\)')
        fallback = re.compile(r'atm#\d+\(([A-Za-z]+)\)_wfc#\d+\(([spdfgpxyz]+)\)')

    file_list = sorted(glob.glob(os.path.join(fatband_dir, '*pdos*')))
    if not file_list:
        raise FileNotFoundError(f"No fatband files matching '*pdos*' found in {fatband_dir}")

    labels = []
    W_list = []
    ik0 = E0 = None
    N_k = N_e = None

    # 2) read and optionally split weights
    for fn in file_list:
        base = os.path.basename(fn)
        m = pattern.search(base)
        if m:
            atom_num, elem, orb = m.groups()
            atom_label = f"{elem}{atom_num}"
        else:
            m2 = fallback.search(base)
            if m2:
                elem, orb = m2.groups()
                atom_label = elem
            else:
                orb = '?'
                atom_label = base

        data = np.loadtxt(fn, comments='#')
        if data.ndim != 2 or data.shape[1] < 3:
            raise ValueError(f"File {fn} needs ≥3 columns (got {data.shape})")

        ik = data[:, 0].astype(int)
        E = data[:, 1]

        # record grid dims on first file
        if ik0 is None:
            ik0, E0 = ik.copy(), E.copy()
            uniq_k = np.unique(ik0)
            N_k = len(uniq_k)
            counts = [np.count_nonzero(ik0 == k) for k in uniq_k]
            # allow truncation if ragged
            if not all(c == counts[0] for c in counts):
                N_e = min(counts)
                print(f"Warning: varying rows per k in {fn}; truncating to N_e={N_e}")
            else:
                N_e = counts[0]
        else:
            # validate subsequent files
            uniq_i = np.unique(ik)
            if len(uniq_i) != N_k:
                raise ValueError(f"File {fn}: unique k count {len(uniq_i)} != expected {N_k}")
            counts_i = [np.count_nonzero(ik == k) for k in uniq_i]
            if not all(c == counts_i[0] for c in counts_i):
                min_e = min(counts_i)
                print(f"Warning: {fn} has varying rows per k; truncating to {min_e}")
                N_e = min(N_e, min_e)
            elif counts_i[0] != N_e:
                N_e = min(N_e, counts_i[0])

        # choose weight columns
        if not sub_orb:
            # 1) Klasik toplam orbital ağırlığı
            w = data[:, 2]
            labels.append((atom_label, orb))
            W_list.append((ik, E, w))

        else:
            ncols = data.shape[1]

            # ---------- SOC (spin=True) dosyaları ----------
            if spin:
                # Dosya adından j değerini çek (örn. "_j1.5")
                m_j = re.search(r'_j([0-9.]+)', base)
                jtag = f"_j{m_j.group(1)}" if m_j else ""

                # k-indeksi, E ve LDOS -> ilk 3 sütun
                pdos_cols = list(range(3, ncols))
                nsub = len(pdos_cols)

                # Varsayılan etiketler (QE sırası: ↑↑ ↓↓ ↑↓_Re ↑↓_Im)
                default_names = ['upup', 'downdown', 'updown_re', 'updown_im']
                subs = [f"{orb}{jtag}_{default_names[i] if i < 4 else f'c{i + 1}'}"
                        for i in range(nsub)]
                cols = pdos_cols

            # ---------- SOC'suz (spin=False) dosyalar ----------
            else:
                nsub = ncols - 2  # LDOS sonrası sütun sayısı

                if orb == 's' and nsub >= 1:
                    cols, subs = ([3], ['s']) if ncols >= 4 else ([2], ['s'])

                elif orb == 'p' and nsub >= 3:
                    cols, subs = [3, 4, 5], ['px', 'py', 'pz']

                elif orb == 'd' and nsub >= 5:
                    cols = [3, 4, 5, 6, 7][:nsub]
                    subs = ['dxy', 'dyz', 'dz2', 'dxz', 'dx2-y2'][:nsub]

                else:  # güvenli geriye dönüş
                    cols, subs = [2], [orb]

            # --------------- Sütunları kaydet ----------------
            for col, sub in zip(cols, subs):
                w = data[:, col]
                labels.append((atom_label, sub))
                W_list.append((ik, E, w))

    # 3) build E_grid and W_grids
    uniq_k = np.unique(ik0)
    E_grid = np.zeros((N_k, N_e))
    for i, kpt in enumerate(uniq_k):
        idxs = np.where(ik0 == kpt)[0][:N_e]
        E_grid[i, :] = E0[idxs]

    W_grids = []
    for ik, E, w in W_list:
        arr = np.zeros((N_k, N_e))
        for i, kpt in enumerate(uniq_k):
            idxs = np.where(ik == kpt)[0][:N_e]
            arr[i, :] = w[idxs]
        W_grids.append(arr)

    return labels, uniq_k, E_grid, W_grids
